### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by dgomes** [carstencodes/simplepycons#2]
Just following up the example in the README:

```
Python 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simplepycons import all_icons, PythonIcon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/venv/lib/python3.12/site-packages/simplepycons/__init__.py", line 15, in <module>
    from .all import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^
  File "/xxx/venv/lib/python3.12/site-packages/simplepycons/all.py", line 19, in <module>
    from ._rubysinatra import RubySinatraIcon
  File "/xxx/venv/lib/python3.12/site-packages/simplepycons/_rubysinatra.py", line 18, in <module>
    from .base_icon import Icon
  File "/xxx/venv/lib/python3.12/site-packages/simplepycons/base_icon.py", line 26, in <module>
    class Icon(ABC):
  File "/xxx/venv/lib/python3.12/site-packages/simplepycons/base_icon.py", line 28, in Icon
    @abstractmethod
     ^^^^^^^^^^^^^^
  File "<frozen abc>", line 24, in abstractmethod
AttributeError: attribute '__isabstractmethod__' of 'property' objects is not writable

```

**Comment by carstencodes** [comment]
The fix is now available on main and will be delivered with next simple-icons version coming tomorrow or on monday.

**Comment by dgomes** [comment]
No release :/ ?

**Comment by carstencodes** [comment]
Sorry, I had a medicinical emergency in the family. Last week was a huge mess.

**Comment by dgomes** [comment]
Sorry to know :( 

Best wishes for the family!
